import { Agent, AgentInput, AgentOutput } from "./types";
import { uploadToYouTube, uploadToTikTok } from "@hec/tools";

export const UploadAgent: Agent = {
  name: "upload-agent",
  async run(input: AgentInput): Promise<AgentOutput> {
    const video = input.video as { path?: string } | undefined;
    const metadata = input.metadata as
      | { title?: string; description?: string }
      | undefined;

    if (!video?.path) {
      return { ...input, upload: { videoUrl: null, clipUrls: [] } };
    }

    const title = metadata?.title ?? "Untitled Hybrid Engine Co. Video";
    const description = metadata?.description ?? "Generated by Hybrid Engine Co.";

    const yt = await uploadToYouTube(video.path, title, description);
    const tt = await uploadToTikTok(video.path, title);

    return {
      ...input,
      upload: {
        videoUrl: yt.url,
        tiktokUrl: tt.url,
        platforms: [yt, tt]
      }
    };
  }
};
