import { Agent, AgentInput, AgentOutput } from "./types";
import { uploadToYouTube, uploadToTikTok } from "@hec/tools";

export const UploadAgent: Agent = {
  name: "upload-agent",
  async run(input: AgentInput): Promise<AgentOutput> {
    const video = input.video as Record<string, string> | undefined;
    const metadata = input.metadata as
      | { title?: string; description?: string; tags?: string[] }
      | undefined;

    if (!video?.["16x9"]) {
      return { ...input, upload: { videoUrl: null, clipUrls: [] } };
    }

    const mainVideoPath = video["16x9"];

    const title = metadata?.title ?? "Untitled Hybrid Engine Co. Video";
    const description = metadata?.description ?? "Generated by Hybrid Engine Co.";
    const tags = metadata?.tags ?? ["Hybrid Engine Co", "content engine"];

    const yt = await uploadToYouTube(mainVideoPath, title, description, tags);
    const tt = await uploadToTikTok(mainVideoPath, title);

    return {
      ...input,
      upload: {
        videoUrl: yt.url,
        tiktokUrl: tt.url,
        platforms: [yt, tt]
      }
    };
  }
};
